/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.admin;

import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Persona;
import modeloDAO.PersonaDao;

/**
 *
 * @author lesly
 */
public class admin_cuenta extends javax.swing.JPanel {

    public admin_cuenta() {
        initComponents();
        mostrarDatos();
        pnlContraseña.setVisible(false);
    }

    public admin_cuenta(String dniObtenido) {
        initComponents();
        dni = dniObtenido;
        mostrarDatos();
        pnlContraseña.setVisible(false);

    }
    String dni;

    private void mostrarDatos() {
        Persona objPersona = new Persona();
        PersonaDao objPersonaDao = new PersonaDao();
        objPersona = objPersonaDao.listarUno(dni);
        txtDNI.setText(objPersona.getDni());
        txtNombre.setText(objPersona.getNombre());
        txtApellido.setText(objPersona.getApellido());
        txtCorreo.setText(objPersona.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlModificar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnModificarContra = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        pnlContraseña = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnActContra = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtContraNueva = new javax.swing.JPasswordField();
        txtRepetirContra = new javax.swing.JPasswordField();

        jButton2.setText("jButton2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 49, 194));
        jLabel1.setText("Mi cuenta");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuenta/Perfil.png"))); // NOI18N

        pnlModificar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("DNI");

        btnModificarContra.setBackground(new java.awt.Color(27, 68, 255));
        btnModificarContra.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnModificarContra.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarContra.setText("Modificar contraseña");
        btnModificarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarContraActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Correo");

        txtDNI.setEditable(false);
        txtDNI.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nombres");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Apellidos");

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));

        btnModificar.setBackground(new java.awt.Color(27, 68, 255));
        btnModificar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar datos");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlModificarLayout = new javax.swing.GroupLayout(pnlModificar);
        pnlModificar.setLayout(pnlModificarLayout);
        pnlModificarLayout.setHorizontalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarLayout.createSequentialGroup()
                        .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlModificarLayout.createSequentialGroup()
                                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(168, 168, 168))
                            .addGroup(pnlModificarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtApellido)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarLayout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnModificarContra)
                        .addGap(91, 91, 91)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlModificarLayout.setVerticalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnModificarContra, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlContraseña.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 49, 194));
        jLabel3.setText("Cambio de contraseña");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Contraseña nueva");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Repetir contraseña");

        btnActContra.setBackground(new java.awt.Color(27, 68, 255));
        btnActContra.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnActContra.setForeground(new java.awt.Color(255, 255, 255));
        btnActContra.setText("Actualizar");
        btnActContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActContraActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(27, 68, 255));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtContraNueva.setForeground(new java.awt.Color(153, 153, 153));
        txtContraNueva.setText("**********");
        txtContraNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraNuevaMousePressed(evt);
            }
        });

        txtRepetirContra.setForeground(new java.awt.Color(153, 153, 153));
        txtRepetirContra.setText("**********");
        txtRepetirContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRepetirContraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContraseñaLayout = new javax.swing.GroupLayout(pnlContraseña);
        pnlContraseña.setLayout(pnlContraseñaLayout);
        pnlContraseñaLayout.setHorizontalGroup(
            pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContraseñaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActContra)
                .addGap(94, 94, 94)
                .addComponent(btnCancelar)
                .addGap(133, 133, 133))
            .addGroup(pnlContraseñaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRepetirContra, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(pnlContraseñaLayout.createSequentialGroup()
                        .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(184, 184, 184))
                    .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        pnlContraseñaLayout.setVerticalGroup(
            pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContraseñaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRepetirContra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActContra)
                    .addComponent(btnCancelar))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(420, 420, 420))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 private void reiniciarPanel() {
        mostrarDatos();
    }

    public void confirmacionAgregar(String a) {
        JOptionPane.showMessageDialog(null, "" + a + " al admin ");
    }

    private boolean validarCorreo(String correo) {
        // Verificar si el correo contiene "@" y ".com"
        return correo.contains("@") && correo.contains(".com");
    }

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Persona objPersona = new Persona();
        PersonaDao objPersonaDao = new PersonaDao();
        objPersona.setDni(dni);
        objPersona.setNombre(txtNombre.getText());
        objPersona.setApellido(txtApellido.getText());
        String correo = txtCorreo.getText();

        if (!validarCorreo(correo)) {
            JOptionPane.showMessageDialog(null, "El correo ingresado no es válido");
            reiniciarPanel();
            return; // Sale del método si el correo no es válido
        }

        objPersona.setEmail(correo);
        objPersonaDao.modificar(objPersona);
        confirmacionAgregar("Se modificó correctamente");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnModificarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarContraActionPerformed
        pnlContraseña.setVisible(true);
        pnlModificar.setVisible(false);
    }//GEN-LAST:event_btnModificarContraActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pnlContraseña.setVisible(false);
        pnlModificar.setVisible(true);    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActContraActionPerformed
        verificacionDeCampos();
//        Persona objPersona = new Persona();
//        PersonaDao objPersonaDao = new PersonaDao();
//        objPersona.setDni(dni);
//        objPersona.setPassword(String.valueOf(txtContraNueva.getPassword()));
//        objPersonaDao.modificarContra(objPersona);
    }//GEN-LAST:event_btnActContraActionPerformed

    public void verificacionDeCampos() {
        int a = 0;
        if (String.valueOf(txtRepetirContra.getPassword()).isEmpty() || String.valueOf(txtRepetirContra.getPassword()).equals("**********")) {
            a = -1;
        }
        if (String.valueOf(txtContraNueva.getPassword()).isEmpty() || String.valueOf(txtContraNueva.getPassword()).equals("**********")) {
            a = -1;
        }
        if (a == 0) {
            verificacionContra();
        }
    }

    public void verificacionContra() {

        if (String.valueOf(txtRepetirContra.getPassword()).equals(String.valueOf(txtContraNueva.getPassword()))) {
            registroAccion();
        } else {
            JOptionPane.showMessageDialog(null, "La contraseña no coinciden", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void registroAccion() {
        Persona objPersona = new Persona();
        PersonaDao objPersonaDao = new PersonaDao();
        objPersona.setDni(dni);
        objPersona.setPassword(String.valueOf(txtContraNueva.getPassword()));

        objPersonaDao.modificarContra(objPersona);

        JOptionPane.showMessageDialog(null, "La contraseña se ha modificado correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        pnlModificar.setVisible(true);

    }
    private void txtContraNuevaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraNuevaMousePressed
        if (String.valueOf(txtContraNueva.getPassword()).equals("**********")) {
            txtContraNueva.setText(null);
            txtContraNueva.setForeground(Color.black);
        }

        if (String.valueOf(txtRepetirContra.getPassword()).isEmpty()) {
            txtRepetirContra.setText("**********");
            txtRepetirContra.setForeground(new Color(204, 204, 204));
        }


    }//GEN-LAST:event_txtContraNuevaMousePressed

    private void txtRepetirContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRepetirContraMousePressed
        if (String.valueOf(txtRepetirContra.getPassword()).equals("**********")) {
            txtRepetirContra.setText(null);
            txtRepetirContra.setForeground(Color.black);
        }

        if (String.valueOf(txtContraNueva.getPassword()).isEmpty()) {
            txtContraNueva.setText("**********");
            txtContraNueva.setForeground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_txtRepetirContraMousePressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActContra;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarContra;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContraseña;
    private javax.swing.JPanel pnlModificar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraNueva;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtRepetirContra;
    // End of variables declaration//GEN-END:variables
}
